### PR TITLE
Add support for Android 10

### PR DESCRIPTION
**Pull request by wizevlad**

### CODE REVIEW

**Comment by eliadAfeka** [comment]
@wizevlad  - are you going to merge it ?

**Comment by glenngr** [comment]
Any news here?

**Comment by tripflex** [comment]
@wizevlad thank you for submitting a PR, can you please fix the formatting in `WifiWizard2.js` as this breaks the diff due to the changes made in the JS file.

@eliadAfeka @glenngr can you confirm that this fixed issues for Android 10?

**Comment by tripflex** [comment]
I believe this is related to and would conflict with https://github.com/tripflex/WifiWizard2/pull/104

Personally I would be in preference of favoring #104 than this one due to all the formatting changes which will make it more difficult to review later on if need to come back to this.

**Comment by glenngr** [comment]
@tripflex I can confirm that #104 fixes the issue. I propose closing this PR and approving #104

**Comment by tripflex** [comment]
@glenngr thanks for confirming, yeah all the formatting changes hurt me head trying to dig through the actual changes in the PR.  I'm going to close this one in favor of merging #104

**Pull request closed without merging**
