### PR TITLE
#71 Prompt to enable location services if device is Android 9+

### PR DESCRIPTION
**Pull request by arsenal942**
### Description of the Change

- Added a check that determines if the device is Android 9+ and if they have location services enabled.
-- If not enabled, it will prompt them to enable them

### Alternate Designs

n/a

### Why Should This Be In Core?

Because the plugin breaks for Android 9+ if we don't have it

### Benefits

Will enable Android 9+ devices to utilise the getConnectionInfo method. The location services enabled check only fires if Android 9+ which is nice because it doesn't annoy users not on Android 9+

### Possible Drawbacks

n/a

### Applicable Issues

#71

### CODE REVIEW

**Comment by arsenal942** [comment]
@tripflex Tried and tested this so I will merge it since it's a critical fix.
I'd still recommend you have a look over it for cleanup/etc.

**Comment by tripflex** [comment]
@eugenioghio thanks for reporting this, are you able to provide any kind of logs when this happens?  Can you try running `adb logcat` with the device connected to see what is being output from android logs -- or maybe any logs from your application?

**Comment by tripflex** [comment]
@arsenal942 from what i can tell -- this is not specific to just Android 9+, but specific to Android 6+ (API 23)

https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

**Comment by arsenal942** [comment]
@tripflex There are some changes that you just have to question and go "Why...."

**Comment by tripflex** [comment]
@arsenal942 yup .. took me a minute to track that down too as it doesn't appear that they have "docs" online from previous API versions which make it hard as hell to figure out when things changed.

For now i'm switching this to >= 23 and going to push this 3.1.1 update, i added a `location` branch which adds checking if location is enabled, going to location setting, but going to push that to 3.2.0 release where i can do more research to see what is required to have location enabled

**Comment by arsenal942** [comment]
Sounds good to me. I still want a log/some information on the device @eugenioghio is using. I've got three devices all of varying API versions between 24-27 and none had any issues with using this method.

We'll just make it a global rule that any device must have them enabled (even if they don't have to).

**Pull request merged**
