### PR TITLE
Add missing callera for setBindAll and resetBindAll

### PR DESCRIPTION
**Pull request by saoron**
Guys, we've missed the invoking conditions for resetBindAll && setBindAll in https://github.com/tripflex/WifiWizard2/pull/74

I've tested the entire sequence with this PR, Sorry about that

### CODE REVIEW

**Comment by saoron** [comment]
@tripflex can you merge this please?

**Comment by arsenal942** [comment]
@saoron Tested? I'm happy with the PR

**Comment by saoron** [comment]
@arsenal942 yes.

**Comment by kalicki** [comment]
@arsenal942 @tripflex I'm using it and I had no problems.

**Comment by tripflex** [comment]
@saoron @kalicki thank you for letting us know, merging ...

**Pull request merged**
